### PR TITLE
add Github Actions

### PR DESCRIPTION
**Pull request by shibumi**
Github is testing an own Continuous Integration system called "Github Actions". This commit adds a workflow for Github Actions. 

Signed-off-by: Christian Rebischke <chris@nullday.de>

### CODE REVIEW

**Comment by svenstaro** [comment]
Keep in mind that this will hopefully at some point run on our own infra.

**Comment by shibumi** [comment]
@svenstaro github supports runner on-premise. We could just use our own runner in the future. No worries from my side.

**Comment by svenstaro** [comment]
Can you link me to that? Last I looked there was nothing yet.

**Comment by shibumi** [comment]
> Can you link me to that? Last I looked there was nothing yet.

https://github.com/features/actions

Mh okay it's marked with `Coming Soon`

**Pull request merged**
