### PR TITLE
Make base image more thin

### PR DESCRIPTION
**Pull request by ogarcia**
- Remove inetutils, iproute2 and iputils unnecessary packages.
- Delete man pages (have not sense in a container).

### CODE REVIEW

**Comment by ogarcia** [comment]
Sorry for first commit using rm to delete man pages. I have not noticed that wildcard are picking the list of files from outside of chroot. :disappointed: 

In the other hand, I'm investigate why fails `pacman-key --populate archlinux`. Seems that depends of iproute2 package, but I dont know why. :open_mouth:

**Comment by ogarcia** [comment]
Ok. I found the issue, seems that `lsign-key` process fail because gpg returns an error code if libusb is not installed.

**Comment by AverageHumanoid** [comment]
Other unnecessary packages in the image include systemd, dbus, iptables and associated dependencies/libraries.

**Comment by ogarcia** [comment]
The bug is closed and the make works well. I think that this PR can be merged.

**Comment by pierres** [comment]
The most minimal setup can be found in the "minimal" branch. I am not sure about this though. We can go two different routes here:
* Provide an image that includes everything from the "base" group except those packages that do not make sense in a container
* Provide everything that is needed to successfully run pacman.

I tend to the latter. This would make using it in interactive mode harder but for just building images that would be fine. Any thoughts?

**Pull request closed without merging**
