### PR TITLE
LICENSE: add license 

### PR DESCRIPTION
**Pull request by SantiagoTorres**
I added a tentative license, although I'm open for anything else

### CODE REVIEW

**Comment by barthalion** [comment]
What licenses other images use?

**Comment by shibumi** [comment]
@barthalion good question. The nginx docker container is under BSD-2 clause... but we are shipping an OS container, that means we have to indicate that our container contains software with different licenses. Ubuntu is doing this like this:
https://hub.docker.com/_/ubuntu/

Centos seems to do the same:
https://hub.docker.com/_/centos/

and Debian as well: 
https://hub.docker.com/_/debian/

**Comment by barthalion** [comment]
I fail to find a license of any of the images you linked to, but admittedly, I didn't click around a lot.

**Comment by shibumi** [comment]
@barthalion this is the point. There is no single license for the container, because we are shipping more than one software. There is just a redirection in the docker container descriptions that leads to a website like this: https://www.ubuntu.com/licensing (for ubuntu for example)

**Comment by SantiagoTorres** [comment]
I looked around and I couldn't find anything about the license for Arch Linux itself... I wonder if this is a broader issue in the way we handle licensing in the distro.

One alternative would be to add a blurb talking about this and that /usr/share/licenses (+other locations) contains licensing information about each package and such.

**Comment by shibumi** [comment]
> I looked around and I couldn't find anything about the license for Arch Linux itself... I wonder if this is a broader issue in the way we handle licensing in the distro.
> 
> One alternative would be to add a blurb talking about this and that /usr/share/licenses (+other locations) contains licensing information about each package and such.

definitley something we should address on one our mailing lists. @barthalion What do you think about a this?

**Comment by barthalion** [comment]
Other distributions like Alpine just point to list of packages available in repositories so I don't see why we wouldn't, it's all here: https://www.archlinux.org/packages/

I thought folks behind Docker Hub are asking about Dockerfile and co., not the resulting image.

**Comment by SantiagoTorres** [comment]
> I thought folks behind Docker Hub are asking about Dockerfile and co., not the resulting image.

I thought so too, but alas

> Other distributions like Alpine just point to list of packages available in repositories so I don't see why we wouldn't, it's all here: https://www.archlinux.org/packages/

Yeah, we could also list the licenses of the packages we are serving somewhere as part of the release then. Let me sketch something on this.

**Comment by pierres** [comment]
Well the license of this repository which contains of scripts to create a docker image can be GPL. The resulting binary has a couple of licenses; similar to our ISO image.

**Comment by SantiagoTorres** [comment]
Ping in here. Time passed and now I'm a little confused: should we leave the GPL license here as is (and merge), and then update it on the library to reflect what alpine and other distributions do?

@pierres @shibumi @barthalion what do you think?

**Comment by shibumi** [comment]
I am fine with it @SantiagoTorres just merge it.

**Pull request merged**
