### PR TITLE
[WIP] use Dockerfile to do anything

### PR DESCRIPTION
**Pull request by zaoqi**
* This make the build process more reproducible and simple
* make `Docker Hub` able to build it

### CODE REVIEW

**Comment by zaoqi** [comment]
This wi

**Comment by shibumi** [comment]
Hi @zaoqi It would be cool if you could provide more description on what you want to achieve. The CI checks are also failing, hope you keep them in mind. Is this PR "Work in progress (WIP)"?

**Comment by zaoqi** [comment]
@shibumi `arch-chroot` needs `mount`, so I was trying to figure out how to run `docker build` in privileged mode

**Comment by SantiagoTorres** [comment]
This is most likely not how we want to go moving forward. This does *not* make the build process more reproducible

**Comment by alerque** [comment]
Github now has a feature called Draft PRs, and you can convert old PRs to that format. This is better that using [WIP] subject line or label hacks for several reasons. It's a bit smarter at handling reviews, blocking merges until it is unmarked as Draft, etc. You can convert using the link in the sidebar under the "reviewers" section.

**Comment by shibumi** [comment]
closing, because this PR doesn't suit our use cases.

**Pull request closed without merging**
